"""Does the hub's `<repo_id>-code` match what the default branch would
produce? (spec 2026-09-25 §4.3a)

Content, not commits: the intake opens no PR when nothing changed, so the
hub's recorded commit may trail main legitimately. L3 only: it is the
machine fact, and L1/L2 of a hub copy published after `kb summarize` differ
without anything having lagged.
"""

from __future__ import annotations

import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from strata_kb import gitio
from strata_kb.codeingest import core, sync

_BANNER_PREFIX = "> Generated by kb code-ingest at "


@dataclass
class LagReport:
    state: Literal["in-sync", "lags", "unknown"]
    reason: str = ""
    ref: str = ""
    ref_date: str = ""
    only_on_main: list[str] = field(default_factory=list)
    only_on_hub: list[str] = field(default_factory=list)
    changed: list[str] = field(default_factory=list)


def l3_sections(doc_dir: Path) -> dict[str, str]:
    """Section id -> L3 body across every `*.raw.md`, banner dropped.
    Headings are `## <id> <title>` (core._render_group)."""
    out: dict[str, str] = {}
    for path in sorted(doc_dir.glob("*.raw.md")):
        current: str | None = None
        body: list[str] = []
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith(_BANNER_PREFIX):
                continue
            if line.startswith("## "):
                if current is not None:
                    out[current] = "\n".join(body).strip()
                current = line[3:].split(" ", 1)[0]
                body = []
            elif current is not None:
                body.append(line)
        if current is not None:
            out[current] = "\n".join(body).strip()
    return out


def check(repo_root: Path, kb_dir: Path, federation_dir: Path, repo_id: str) -> LagReport:
    doc_id = f"{repo_id}-code"
    pin_note = sync.version_note(repo_root)
    if pin_note:
        return LagReport("unknown", reason=pin_note)
    hub_doc = federation_dir / repo_id / doc_id
    if not (hub_doc / "_manifest.yaml").exists():
        return LagReport("unknown", reason=f"the hub has no {doc_id} yet")
    if not gitio.has_remote(repo_root):
        return LagReport("unknown", reason="no git remote — nothing to compare the hub with")
    ref = f"origin/{gitio.default_branch(repo_root)}"
    if not gitio.rev_exists(repo_root, ref):
        return LagReport("unknown", reason=f"no local ref {ref} — run `git fetch`", ref=ref)
    ref_date = core._git(repo_root, "show", "-s", "--format=%cs", ref).stdout.strip()
    base = sync.options_from_config(repo_root, kb_dir, repo_id)
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "main"
        try:
            gitio.worktree_add_detached(repo_root, work, ref)
        except gitio.GitError as exc:
            return LagReport("unknown", reason=str(exc), ref=ref, ref_date=ref_date)
        try:
            # kb_dir inside the worktree, so the tree extractor prunes the
            # worktree's own .kb/ exactly as a real checkout's is pruned.
            core.run(core.CodeIngestOptions(
                repo_root=work, kb_dir=work / ".kb", doc_id=doc_id, repo_id=repo_id,
                db_paths=base.db_paths, tags=base.tags,
            ))
            main = l3_sections(work / ".kb" / doc_id)
        except core.CodeIngestError as exc:
            return LagReport(
                "unknown", reason=f"code-ingest failed at {ref}: {exc}",
                ref=ref, ref_date=ref_date,
            )
        finally:
            gitio.worktree_remove(repo_root, work)
    hub = l3_sections(hub_doc)
    only_main = sorted(main.keys() - hub.keys())
    only_hub = sorted(hub.keys() - main.keys())
    changed = sorted(k for k in main.keys() & hub.keys() if main[k] != hub[k])
    state = "lags" if (only_main or only_hub or changed) else "in-sync"
    return LagReport(state, ref=ref, ref_date=ref_date,
                     only_on_main=only_main, only_on_hub=only_hub, changed=changed)
