"""Does the hub's `<repo_id>-code` match what the default branch would
produce? (spec 2026-09-25 §4.3a)

Content, not commits: the intake opens no PR when nothing changed, so the
hub's recorded commit may trail main legitimately. L3 only: it is the
machine fact, and L1/L2 of a hub copy published after `kb summarize` differ
without anything having lagged.
"""

from __future__ import annotations

import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from strata_kb import gitio
from strata_kb.codeingest import core, sync

_BANNER_PREFIX = "> Generated by kb code-ingest at "


@dataclass
class LagReport:
    state: Literal["in-sync", "lags", "unknown"]
    reason: str = ""
    ref: str = ""
    ref_date: str = ""
    only_on_main: list[str] = field(default_factory=list)
    only_on_hub: list[str] = field(default_factory=list)
    changed: list[str] = field(default_factory=list)


def l3_sections(doc_dir: Path) -> dict[str, str]:
    """Section id -> L3 body across every `*.raw.md`, banner dropped.
    Headings are `## <id> <title>` (core._render_group)."""
    out: dict[str, str] = {}
    for path in sorted(doc_dir.glob("*.raw.md")):
        current: str | None = None
        body: list[str] = []
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith(_BANNER_PREFIX):
                continue
            if line.startswith("## "):
                if current is not None:
                    out[current] = "\n".join(body).strip()
                current = line[3:].split(" ", 1)[0]
                body = []
            elif current is not None:
                body.append(line)
        if current is not None:
            out[current] = "\n".join(body).strip()
    return out


def _worktree_db_paths(
    repo_root: Path, work: Path, db_paths: tuple[Path, ...]
) -> tuple[Path, ...]:
    """Copy each `--db` path that lives under `repo_root` to the same
    relative path inside `work` (the detached worktree) and return the
    worktree-side paths; a path outside `repo_root` is returned unchanged.

    `core.run(repo_root=work, ...)` otherwise hands the schema extractor an
    ABSOLUTE path into the real checkout, which `schema._path_label` cannot
    relativize against `work` -- it falls back to `--db:<basename>` in L3,
    while CI (whose `repo_root` IS the checkout) writes the familiar
    `data/app.sqlite` label, so every schema section compares as "changed"
    even when nothing did. The database's CONTENT still comes from the real
    checkout, never from the worktree's git tree (spec §4.3a step 2: a `--db`
    path is data, not code, and `origin/main`'s commit never carries it) --
    only the path handed to code-ingest is relocated, so the label matches.
    """
    out: list[Path] = []
    for db_path in db_paths:
        try:
            rel = db_path.relative_to(repo_root)
        except ValueError:
            out.append(db_path)
            continue
        dest = work / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(db_path, dest)
        out.append(dest)
    return tuple(out)


def check(repo_root: Path, kb_dir: Path, federation_dir: Path, repo_id: str) -> LagReport:
    doc_id = f"{repo_id}-code"
    pin_note = sync.version_note(repo_root)
    if pin_note:
        return LagReport("unknown", reason=pin_note)
    hub_doc = federation_dir / repo_id / doc_id
    if not (hub_doc / "_manifest.yaml").exists():
        return LagReport("unknown", reason=f"the hub has no {doc_id} yet")
    if not gitio.has_remote(repo_root):
        return LagReport("unknown", reason="no git remote — nothing to compare the hub with")
    try:
        # origin/HEAD only -- never the branch that happens to be checked
        # out (controller ruling: gitio.default_branch's fallback would
        # otherwise let a feature branch stand in for "main" right after
        # `git remote add` + `push -u`, before anyone runs `git remote
        # set-head origin --auto`).
        ref = gitio.origin_head_ref(repo_root)
    except gitio.GitError as exc:
        return LagReport("unknown", reason=str(exc))
    if not gitio.rev_exists(repo_root, ref):
        return LagReport("unknown", reason=f"no local ref {ref} — run `git fetch`", ref=ref)
    ref_date = core._git(repo_root, "show", "-s", "--format=%cs", ref).stdout.strip()
    base = sync.options_from_config(repo_root, kb_dir, repo_id)
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "main"
        try:
            gitio.worktree_add_detached(repo_root, work, ref)
        except gitio.GitError as exc:
            return LagReport("unknown", reason=str(exc), ref=ref, ref_date=ref_date)
        try:
            work_db_paths = _worktree_db_paths(repo_root, work, base.db_paths)
            # kb_dir inside the worktree, so the tree extractor prunes the
            # worktree's own .kb/ exactly as a real checkout's is pruned.
            core.run(core.CodeIngestOptions(
                repo_root=work, kb_dir=work / ".kb", doc_id=doc_id, repo_id=repo_id,
                db_paths=work_db_paths, tags=base.tags,
            ))
            main = l3_sections(work / ".kb" / doc_id)
        except core.CodeIngestError as exc:
            return LagReport(
                "unknown", reason=f"code-ingest failed at {ref}: {exc}",
                ref=ref, ref_date=ref_date,
            )
        except OSError as exc:
            # A `kb doctor` check must never abort the whole command --
            # "cannot judge" (unknown) beats a traceback, same reasoning as
            # the CodeIngestError branch just above (e.g. a --db path that
            # vanished between `options_from_config` and the copy above).
            return LagReport(
                "unknown", reason=f"could not prepare {ref} for comparison: {exc}",
                ref=ref, ref_date=ref_date,
            )
        finally:
            gitio.worktree_remove(repo_root, work)
    hub = l3_sections(hub_doc)
    only_main = sorted(main.keys() - hub.keys())
    only_hub = sorted(hub.keys() - main.keys())
    changed = sorted(k for k in main.keys() & hub.keys() if main[k] != hub[k])
    state = "lags" if (only_main or only_hub or changed) else "in-sync"
    return LagReport(state, ref=ref, ref_date=ref_date,
                     only_on_main=only_main, only_on_hub=only_hub, changed=changed)
