import shutil
import sqlite3
from pathlib import Path

import pytest
from typer.testing import CliRunner

import strata_kb
from strata_kb.cli import app
from strata_kb.codeingest import core, hublag, sync
from tests.fixtures_coderepo import build_code_repo


@pytest.fixture
def clone(tmp_path, run_git):
    src = tmp_path / "src"
    src.mkdir()
    build_code_repo(src)
    (src / ".kb").mkdir(exist_ok=True)
    (src / ".kb" / "config.yaml").write_text('kind: dev\nrepo_id: "demo"\n', encoding="utf-8")
    (src / ".gitignore").write_text(".kb/*-code/\n", encoding="utf-8")
    run_git(src, "init", "-b", "main")
    run_git(src, "add", "-A")
    run_git(src, "commit", "-m", "init")
    bare = tmp_path / "origin.git"
    run_git(tmp_path, "clone", "--bare", str(src), str(bare))
    work = tmp_path / "clone"
    run_git(tmp_path, "clone", str(bare), str(work))
    return work


def _publish(clone: Path, fed: Path) -> None:
    """The hub copy CI would publish for the clone's current commit."""
    core.run(core.CodeIngestOptions(
        repo_root=clone, kb_dir=clone / ".kb", doc_id="demo-code", repo_id="demo",
    ))
    dest = fed / "demo" / "demo-code"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(clone / ".kb" / "demo-code", dest)


def test_l3_sections_split_by_heading_and_drop_the_banner(tmp_path):
    doc = tmp_path / "doc"
    doc.mkdir()
    (doc / "services.raw.md").write_text(
        "# demo-code\n\n> Generated by kb code-ingest at abc1234 — do not edit by hand.\n\n"
        "## svc.a Service a\n\nbody a\n\n## svc.b Service b\n\nbody b\n",
        encoding="utf-8",
    )
    assert hublag.l3_sections(doc) == {"svc.a": "body a", "svc.b": "body b"}


def test_in_sync_when_the_hub_matches_main(clone, tmp_path):
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)
    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "in-sync", report


def test_lags_when_main_moved_past_the_hub(clone, tmp_path, run_git):
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)
    (clone / "compose.billing.yml").write_text(
        "services:\n  billing-service:\n    image: billing:1\n", encoding="utf-8"
    )
    run_git(clone, "add", "-A")
    run_git(clone, "commit", "-m", "billing")
    run_git(clone, "push", "origin", "main")
    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "lags"
    assert any("billing" in s for s in report.only_on_main)
    assert report.ref == "origin/main"


def test_in_sync_with_a_configured_db_path(clone, tmp_path):
    """Fix round 1, Important 1: a `--db` path resolved from
    `code_ingest.db` is an ABSOLUTE path into the real checkout, and
    `core.run` inside `check()` is called with `repo_root=work` (the
    detached worktree) -- without relocating the file alongside the
    worktree, `schema._path_label` cannot relativize it against `work` and
    falls back to `--db:<basename>` in L3, which never matches the label
    CI wrote (`data/app.sqlite`) and reports a false "lags" verdict on an
    otherwise identical repo."""
    (clone / ".kb" / "config.yaml").write_text(
        'kind: dev\nrepo_id: "demo"\ncode_ingest:\n  db: ["data/app.sqlite"]\n',
        encoding="utf-8",
    )
    (clone / "data").mkdir()
    # Untracked, the way a real repo gitignores its local database (the
    # same reasoning `.kb/*-code/` is gitignored): a --db path is data code
    # -ingest reads straight off the working tree, never a file `origin/
    # main`'s commit could carry (spec §4.3a step 2) -- which is exactly
    # why `check()` must relocate it into the worktree itself rather than
    # relying on the checkout to already have it.
    con = sqlite3.connect(str(clone / "data" / "app.sqlite"))
    con.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)")
    con.commit()
    con.close()

    fed = tmp_path / "hub" / "federation"
    # Published the way CI would: `sync.options_from_config` reads the
    # same `code_ingest.db` config this test just wrote.
    opts = sync.options_from_config(clone, clone / ".kb", "demo")
    core.run(opts)
    dest = fed / "demo" / "demo-code"
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(clone / ".kb" / "demo-code", dest)

    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "in-sync", report


def test_unknown_when_origin_head_is_not_set(clone, tmp_path, run_git):
    """Fix round 1, Important 2: `gitio.default_branch` falls back to the
    checked-out branch when `refs/remotes/origin/HEAD` is unset -- common
    right after `git remote add` + `push -u`, before anyone runs `git
    remote set-head origin --auto` -- which would silently compare the hub
    against a feature branch. hublag must refuse to guess instead."""
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)
    run_git(clone, "remote", "set-head", "origin", "--delete")
    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "unknown"
    assert "set-head" in report.reason


def test_worktree_is_removed_afterwards(clone, tmp_path, run_git):
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)
    hublag.check(clone, clone / ".kb", fed, "demo")
    assert len(run_git(clone, "worktree", "list").splitlines()) == 1


def test_unknown_on_a_version_pin_mismatch(clone, tmp_path, monkeypatch):
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)
    wf = clone / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "kb-code.yml").write_text("- run: pip install strata-kb==0.0.1\n", encoding="utf-8")
    monkeypatch.setattr(strata_kb, "__version__", "1.4.0")
    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "unknown" and "pins 0.0.1" in report.reason


def test_unknown_without_a_remote(tmp_path, run_git):
    root = tmp_path / "solo"
    root.mkdir()
    build_code_repo(root)
    run_git(root, "init")
    run_git(root, "add", "-A")
    run_git(root, "commit", "-m", "init")
    fed = tmp_path / "hub" / "federation"
    (fed / "demo" / "demo-code").mkdir(parents=True)
    (fed / "demo" / "demo-code" / "_manifest.yaml").write_text("id: demo-code\ntitle: t\n", encoding="utf-8")
    report = hublag.check(root, root / ".kb", fed, "demo")
    assert report.state == "unknown" and "remote" in report.reason


def test_worktree_is_removed_when_code_ingest_fails(clone, tmp_path, run_git, monkeypatch):
    """Controller ruling: spec §6 requires the worktree to be removed on
    failure too, not only on the happy path (test_worktree_is_removed_
    afterwards above only exercises the happy path)."""
    fed = tmp_path / "hub" / "federation"
    _publish(clone, fed)

    def _boom(opts):
        raise core.CodeIngestError("boom")

    monkeypatch.setattr(hublag.core, "run", _boom)
    report = hublag.check(clone, clone / ".kb", fed, "demo")
    assert report.state == "unknown"
    assert "boom" in report.reason
    assert len(run_git(clone, "worktree", "list").splitlines()) == 1


def test_kb_doctor_reports_dev_sync_and_hub_lag_together(clone, tmp_path):
    """Controller ruling: the dev branch `kb doctor` wires check_dev_sync and
    check_hub_lag together (cli.py, Task 11's Step 6) — no earlier test
    exercised that wiring at the CLI layer. Uses a hub with no `demo-code`
    entry yet, which is the cheapest way to reach the "unknown" hub-lag
    branch without also standing up a real `origin/main` checkout."""
    (clone / ".kb" / "index.yaml").write_text("docs: []\n", encoding="utf-8")
    wf = clone / ".github" / "workflows"
    wf.mkdir(parents=True, exist_ok=True)
    (wf / "kb-code.yml").write_text(
        "on: [push]\njobs:\n  code:\n    steps:\n"
        "      - run: kb code-ingest --db data/app.sqlite\n",
        encoding="utf-8",
    )

    hub = tmp_path / "hub"
    (hub / ".kb").mkdir(parents=True)
    (hub / ".kb" / "index.yaml").write_text("docs: []\n", encoding="utf-8")
    fed = hub / "federation"
    fed.mkdir()
    from strata_kb.federation import write_federation_index

    write_federation_index(fed)

    runner = CliRunner()
    result = runner.invoke(
        app, ["doctor", "--kb-dir", str(clone / ".kb"), "--hub", str(hub)]
    )

    assert "kb-code.yml passes --db" in result.output, result.output
    assert "hub lag not judged" in result.output, result.output
