"""T2 — packaging check. Pure stdlib: runs in any venv.

    python scripts/check_package.py --venv /tmp/artifact --dist dist [--tag v0.9.1]

Catches five classes of mistake:
  1. kb --version (from the INSTALLED WHEEL) differs from pyproject.version
  2. tag differs from pyproject.version  (only when --tag is given)
  3. wheel contains anything beyond the real package + dist-info
  4. sdist contains anything beyond src/ + the metadata files hatchling adds
     itself — by default hatchling stuffs everything not gitignored into the
     sdist, and .kb/ holds text quoted verbatim from copyrighted PDFs, so
     slipping into the sdist ships it out to PyPI just as surely as slipping
     into the wheel
  5. dist/ does not have both a wheel and an sdist

Items 3+4 use an ALLOWLIST (what is permitted), not a denylist (what is
forbidden): a denylist only catches the names someone thought of and wrote
down — it once let `AERO-KB_Architecture_v0.1.pdf` at the root, `.claude/`,
`.github/`, and `scripts/` slip through because nobody had listed them, and it
rots a little further every time the repo grows another new top-level
directory. An allowlist is shorter AND tighter: anything not on the
known-to-be-good list gets flagged, with no need to guess bad names up front.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

# ---- Wheel: may hold only the real package + the wheel's standard metadata dir. ----
# The directory name `<name>-<version>.dist-info/` changes with the version on
# every build, so compare by suffix rather than hardcoding the version.
WHEEL_PACKAGE_DIR = "center_kb"
WHEEL_DIST_INFO_SUFFIX = ".dist-info"

# ---- sdist: src/ (the real source) + the metadata files hatchling ALWAYS adds
# itself, unconditionally, to EVERY sdist target, no matter what only-include says.
# pyproject.toml/README/LICENSE: per the comment at [tool.hatch.build.targets.sdist]
# in pyproject.toml. PKG-INFO: generated by the sdist build step itself. .gitignore:
# confirmed empirically (built one, then listed the real contents — not guessed).
SDIST_ALLOWED_TOP_LEVEL = {
    "src", "PKG-INFO", "pyproject.toml", "README.md", "LICENSE", ".gitignore",
}


def pyproject_version(root: Path) -> str:
    for line in (root / "pyproject.toml").read_text(encoding="utf-8").splitlines():
        if line.startswith("version ="):
            return line.split("=", 1)[1].strip().strip('"')
    raise RuntimeError("`version =` not found in pyproject.toml")


def tag_matches(tag: str, version: str) -> bool:
    return tag.removeprefix("v") == version


def wheel_offenders(wheel: Path) -> list[str]:
    tops = set()
    with zipfile.ZipFile(wheel) as zf:
        for name in zf.namelist():
            tops.add(name.split("/", 1)[0])
    allowed = {WHEEL_PACKAGE_DIR} | {t for t in tops if t.endswith(WHEEL_DIST_INFO_SUFFIX)}
    return sorted(tops - allowed)


def sdist_offenders(sdist: Path) -> list[str]:
    # An sdist tarball nests every entry under a root dir `<name>-<version>/` —
    # the REAL top-level is the SECOND path segment, not the first as in a wheel.
    tops = set()
    with tarfile.open(sdist, "r:gz") as tf:
        for name in tf.getnames():
            parts = name.split("/", 2)
            if len(parts) > 1:
                tops.add(parts[1])
    return sorted(tops - SDIST_ALLOWED_TOP_LEVEL)


def installed_version(venv: Path) -> str:
    proc = subprocess.run(
        [str(venv / "bin" / "kb"), "--version"],
        capture_output=True, text=True, timeout=60,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"`kb --version` failed: {proc.stderr}")
    return proc.stdout.strip()


def check(venv: Path, dist: Path, root: Path, tag: str | None) -> list[str]:
    errors: list[str] = []
    declared = pyproject_version(root)

    wheels = sorted(dist.glob("*.whl"))
    sdists = sorted(dist.glob("*.tar.gz"))
    if not wheels:
        errors.append(f"{dist}/ has no wheel at all")
    if not sdists:
        errors.append(f"{dist}/ has no sdist at all")

    got = installed_version(venv)
    if got != declared:
        errors.append(f"`kb --version` = {got!r} but pyproject.version = {declared!r}")

    for wheel in wheels:
        offenders = wheel_offenders(wheel)
        if offenders:
            errors.append(f"{wheel.name} wrongly packages: {', '.join(offenders)}")

    for sdist in sdists:
        offenders = sdist_offenders(sdist)
        if offenders:
            errors.append(f"{sdist.name} wrongly packages: {', '.join(offenders)}")

    if tag and not tag_matches(tag, declared):
        errors.append(f"tag {tag!r} differs from pyproject.version {declared!r}")

    return errors


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--venv", type=Path, required=True, help="venv with the wheel installed")
    ap.add_argument("--dist", type=Path, default=Path("dist"))
    ap.add_argument("--root", type=Path, default=Path(__file__).parent.parent)
    ap.add_argument("--tag", default=None, help="git tag, e.g. v0.9.1 (only on release)")
    args = ap.parse_args()

    errors = check(args.venv, args.dist, args.root, args.tag)
    for err in errors:
        print(f"[error] {err}", file=sys.stderr)
    if errors:
        return 1
    print("check_package: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
